import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import FetchExample from '../components/FetchExample'
import AsyncAwaitExample from '../components/AsyncAwaitExample'
import AxiosExample from '../components/AxiosExample'
import ReactQueryExample from '../components/ReactQueryExample'
import {UseFetchExample} from '../components/UseFetchExample'
import { QueryClient, QueryClientProvider} from 'react-query';
const inter = Inter({ subsets: ['latin'] })

const queryClient = new QueryClient();

export default function Home() {
  const posts = UseFetchExample('https://jsonplaceholder.typicode.com/posts');
  console.log("posts: ", posts)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
      <QueryClientProvider client={queryClient}>
        <ReactQueryExample/>
      </QueryClientProvider>
        
        <h2>Custom Hook Example</h2>
        {posts.map((post) => (
          <div key={post.id}>
            <h3>{post.title}</h3>
            <p>{post.body}</p>
          </div>
        ))}
        <AxiosExample/>
        <AsyncAwaitExample/>
        <FetchExample/>
      </main>
    </>
  )
}
